using Mutagen.Bethesda;
using Mutagen.Bethesda.Skyrim;
using Mutagen.Bethesda.Synthesis;
using System.Text.Json.Nodes;

namespace ReProccer;
static class Executor
{
    internal static IPatcherState<ISkyrimMod, ISkyrimModGetter>? State;

    internal static Lazy<Config.SettingsUI> SettingsUI = new();
    internal static readonly Lazy<Config.General> General = new();

    // entry point
    public static async Task<int> Main(string[] args)
    {
        return await SynthesisPipeline.Instance
        .AddPatch<ISkyrimMod, ISkyrimModGetter>(Initialize)
        .SetAutogeneratedSettings("ReProccer Evolved", "settings/settings.json", out SettingsUI)
        .SetTypicalOpen(GameRelease.SkyrimSE, "ReProccer.esp")
        .Run(args);
    }

    // init process
    public static void Initialize(IPatcherState<ISkyrimMod, ISkyrimModGetter> patcherState)
    {
        Console.WriteLine("");

        // getting state
        State = patcherState;
		
        // loading strings	
        JsonNode stringsJson = Utils.Helpers.LoadJson($"{AppContext.BaseDirectory}locales", "english.jsonc", true);

        string[] jsonFiles = [.. Directory.GetFiles($"{AppContext.BaseDirectory}locales", "*.json*")
        .Where(name => !name.Contains("english.jsonc"))
        .Select(file => Path.GetFileName(file))];

        if (jsonFiles.Length > 0)
        {
            foreach (var file in jsonFiles)
            {
                JsonNode locStrings = Utils.Helpers.LoadJson($"{AppContext.BaseDirectory}locales", file);
                stringsJson = Utils.Helpers.DeepMerge(stringsJson, locStrings);
            }
        }

        Strings = stringsJson!.AsObject();
    }
}