using Mutagen.Bethesda.Skyrim;
using Mutagen.Bethesda.Synthesis;
using ReProccer.Config;
using ReProccer.Utils;
using System.Text.Json.Nodes;

namespace ReProccer;

static class Executor
{
    internal static JsonObject? Strings;
    internal static JsonObject? Rules;
    internal static List<StaticsMap>? Statics;
    internal static IPatcherState<ISkyrimMod, ISkyrimModGetter>? State;

    internal static Lazy<AllSettings> AllSettings = new();
    internal static AllSettings? Settings;

    // entry point
    public static async Task<int> Main(string[] args)
    {
        return await SynthesisPipeline.Instance
        .AddPatch<ISkyrimMod, ISkyrimModGetter>(Initialize)
        .SetAutogeneratedSettings("Settings", "Settings.json", out AllSettings)
        .SetTypicalOpen(Mutagen.Bethesda.GameRelease.SkyrimSE, "ReProccer.esp")
        .Run(args);
    }

    // init process
    public static void Initialize(IPatcherState<ISkyrimMod, ISkyrimModGetter> patcherState)
    {
        // initiating settings
        Settings = AllSettings.Value;

        Console.WriteLine("");

        // getting state
        State = patcherState;

        // loading strings	
        JsonNode stringsJson = Helpers.LoadJson($"{AppContext.BaseDirectory}locales", "english.jsonc", true);

        string[] jsonFiles = [.. Directory.GetFiles($"{AppContext.BaseDirectory}locales", "*.json*")
        .Where(name => !name.Contains("english.jsonc"))
        .Select(file => Path.GetFileName(file))];

        if (jsonFiles.Length > 0)
        {
            foreach (var file in jsonFiles)
            {
                JsonNode locStrings = Helpers.LoadJson($"{AppContext.BaseDirectory}locales", file);
                stringsJson = Helpers.DeepMerge(stringsJson, locStrings);
            }
        }

        Strings = stringsJson!.AsObject();

        // building rules
        var loadOrder = State.LoadOrder;

        if (!loadOrder.Any(file => file.Key.FileName.Equals("Skyrim AE Redone - Core.esm")))
        {
            throw new Exception("\n--> Skyrim AE Redone - Core.esm should be active in the load order!\n");
        }

        if (!loadOrder.Any(file => file.Key.FileName.Equals("Skyrim AE Redone - Main.esp")))
        {
            throw new Exception("\n--> The patching is only required if the Main Module is installed\n");
        }

        JsonNode rulesJson = Helpers.LoadJson($"{AppContext.BaseDirectory}rules", "_rules-basic.jsonc");

        foreach (var file in loadOrder)
        {
            if (!file.Value.Enabled || Settings.General.IgnoredFiles.Any(name => name == file.Key.FileName)) continue;

            string[] match = Directory.GetFiles($"{AppContext.BaseDirectory}rules", $"{file.Key.Name}.json*");
            if (match.Length == 0) continue;

            JsonNode pluginRules = Helpers.LoadJson($"{AppContext.BaseDirectory}rules", $"{Path.GetFileName(match[0])}", true);
            rulesJson = Helpers.DeepMerge(rulesJson, pluginRules);
        }

        JsonNode userRules = Helpers.LoadJson($"{AppContext.BaseDirectory}rules", "_rules-user.jsonc", true);
        rulesJson = Helpers.DeepMerge(rulesJson, userRules);
        Rules = rulesJson!.AsObject();

        // parsing statics
        Statics = BuildStatics();

        // running patchers
        if (Settings.General.ArmorPatcher) Patchers.ArmorPatcher.Run();
    }

    private static List<StaticsMap> BuildStatics() => [
            new(Id: "fArmorScalingFactor",                    Formkey: Helpers.ParseFormKey("Skyrim.esm|00021a72|GMST")                  ),
            new(Id: "fMaxArmorRating",                        Formkey: Helpers.ParseFormKey("Skyrim.esm|00037deb|GMST")                  ),
            new(Id: "DLC1BoltExplosionFire02",                Formkey: Helpers.ParseFormKey("Dawnguard.esm|00010d90|EXPL")               ),
            new(Id: "DLC1BoltExplosionFrost02",               Formkey: Helpers.ParseFormKey("Dawnguard.esm|00010d91|EXPL")               ),
            new(Id: "DLC1BoltExplosionShock02",               Formkey: Helpers.ParseFormKey("Dawnguard.esm|00010d92|EXPL")               ),
            new(Id: "skyre_ALCExplosiveArrow0Explosion",      Formkey: Helpers.ParseFormKey("Skyrim AE Redone - Core.esm|00000854|EXPL") ),
            new(Id: "skyre_ALCAshenArrowExplosion",           Formkey: Helpers.ParseFormKey("Skyrim AE Redone - Core.esm|00000876|EXPL") ),
            new(Id: "Charcoal",                               Formkey: Helpers.ParseFormKey("Skyrim.esm|00033760|MISC")                  ),
            new(Id: "RuinsLinenPile01",                       Formkey: Helpers.ParseFormKey("Skyrim.esm|00034cd6|MISC")                  ),
            new(Id: "ChaurusChitin",                          Formkey: Helpers.ParseFormKey("Skyrim.esm|0003ad57|MISC")                  ),
            new(Id: "DragonScales",                           Formkey: Helpers.ParseFormKey("Skyrim.esm|0003ada3|MISC")                  ),
            new(Id: "DragonBone",                             Formkey: Helpers.ParseFormKey("Skyrim.esm|0003ada4|MISC")                  ),
            new(Id: "IngotCorundum",                          Formkey: Helpers.ParseFormKey("Skyrim.esm|0005ad93|MISC")                  ),
            new(Id: "IngotOrichalcum",                        Formkey: Helpers.ParseFormKey("Skyrim.esm|0005ad99|MISC")                  ),
            new(Id: "IngotEbony",                             Formkey: Helpers.ParseFormKey("Skyrim.esm|0005ad9d|MISC")                  ),
            new(Id: "IngotGold",                              Formkey: Helpers.ParseFormKey("Skyrim.esm|0005ad9e|MISC")                  ),
            new(Id: "IngotMoonstone",                         Formkey: Helpers.ParseFormKey("Skyrim.esm|0005ad9f|MISC")                  ),
            new(Id: "IngotQuicksilver",                       Formkey: Helpers.ParseFormKey("Skyrim.esm|0005ada0|MISC")                  ),
            new(Id: "IngotMalachite",                         Formkey: Helpers.ParseFormKey("Skyrim.esm|0005ada1|MISC")                  ),
            new(Id: "IngotSilver",                            Formkey: Helpers.ParseFormKey("Skyrim.esm|0005ace3|MISC")                  ),
            new(Id: "IngotIron",                              Formkey: Helpers.ParseFormKey("Skyrim.esm|0005ace4|MISC")                  ),
            new(Id: "IngotSteel",                             Formkey: Helpers.ParseFormKey("Skyrim.esm|0005ace5|MISC")                  ),
            new(Id: "Firewood01",                             Formkey: Helpers.ParseFormKey("Skyrim.esm|0006f993|MISC")                  ),
            new(Id: "LeatherStrips",                          Formkey: Helpers.ParseFormKey("Skyrim.esm|000800e4|MISC")                  ),
            new(Id: "Leather01",                              Formkey: Helpers.ParseFormKey("Skyrim.esm|000db5d2|MISC")                  ),
            new(Id: "IngotDwarven",                           Formkey: Helpers.ParseFormKey("Skyrim.esm|000db8a2|MISC")                  ),
            new(Id: "DLC2NetchLeather",                       Formkey: Helpers.ParseFormKey("Dragonborn.esm|0001cd7c|MISC")              ),
            new(Id: "DLC2ChitinPlate",                        Formkey: Helpers.ParseFormKey("Dragonborn.esm|0002b04e|MISC")              ),
            new(Id: "DLC2OreStalhrim",                        Formkey: Helpers.ParseFormKey("Dragonborn.esm|0002b06b|MISC")              ),
            new(Id: "cc_IngotAmber",                          Formkey: Helpers.ParseFormKey("ccBGSSSE025-AdvDSGS.esm|00000bc7|MISC")     ),
            new(Id: "cc_IngotMadness",                        Formkey: Helpers.ParseFormKey("ccBGSSSE025-AdvDSGS.esm|00000bc8|MISC")     ),
            new(Id: "SoulGemPettyFilled",                     Formkey: Helpers.ParseFormKey("Skyrim.esm|0002e4e3|SLGM")                  ),
            new(Id: "SoulGemLesserFilled",                    Formkey: Helpers.ParseFormKey("Skyrim.esm|0002e4e5|SLGM")                  ),
            new(Id: "SoulGemCommonFilled",                    Formkey: Helpers.ParseFormKey("Skyrim.esm|0002e4f3|SLGM")                  ),
            new(Id: "FireSalt",                               Formkey: Helpers.ParseFormKey("Skyrim.esm|0003ad5e|INGR")                  ),
            new(Id: "FrostSalt",                              Formkey: Helpers.ParseFormKey("Skyrim.esm|0003ad5f|INGR")                  ),
            new(Id: "VoidSalt",                               Formkey: Helpers.ParseFormKey("Skyrim.esm|0003ad60|INGR")                  ),
            new(Id: "TrollFat",                               Formkey: Helpers.ParseFormKey("Skyrim.esm|0003ad72|INGR")                  ),
            new(Id: "glowDust",                               Formkey: Helpers.ParseFormKey("Skyrim.esm|0003ad73|INGR")                  ),
            new(Id: "SprigganSap",                            Formkey: Helpers.ParseFormKey("Skyrim.esm|00063b5f|INGR")                  ),
            new(Id: "WispWrappings",                          Formkey: Helpers.ParseFormKey("Skyrim.esm|0006bc0e|INGR")                  ),
            new(Id: "DwarvenOil",                             Formkey: Helpers.ParseFormKey("Skyrim.esm|000f11c0|INGR")                  ),
            new(Id: "DLC2GhoulAsh",                           Formkey: Helpers.ParseFormKey("Dragonborn.esm|0001cd6d|INGR")              ),
            new(Id: "WeapTypeSword",                          Formkey: Helpers.ParseFormKey("Skyrim.esm|0001e711|KWDA")                  ),
            new(Id: "WeapTypeWaraxe",                         Formkey: Helpers.ParseFormKey("Skyrim.esm|0001e712|KWDA")                  ),
            new(Id: "WeapTypeDagger",                         Formkey: Helpers.ParseFormKey("Skyrim.esm|0001e713|KWDA")                  ),
            new(Id: "WeapTypeMace",                           Formkey: Helpers.ParseFormKey("Skyrim.esm|0001e714|KWDA")                  ),
            new(Id: "WeapTypeBow",                            Formkey: Helpers.ParseFormKey("Skyrim.esm|0001e715|KWDA")                  ),
            new(Id: "WeapMaterialWood",                       Formkey: Helpers.ParseFormKey("Skyrim.esm|0001e717|KWDA")                  ),
            new(Id: "WeapMaterialIron",                       Formkey: Helpers.ParseFormKey("Skyrim.esm|0001e718|KWDA")                  ),
            new(Id: "WeapMaterialSteel",                      Formkey: Helpers.ParseFormKey("Skyrim.esm|0001e719|KWDA")                  ),
            new(Id: "WeapMaterialDwarven",                    Formkey: Helpers.ParseFormKey("Skyrim.esm|0001e71a|KWDA")                  ),
            new(Id: "WeapMaterialElven",                      Formkey: Helpers.ParseFormKey("Skyrim.esm|0001e71b|KWDA")                  ),
            new(Id: "WeapMaterialOrcish",                     Formkey: Helpers.ParseFormKey("Skyrim.esm|0001e71c|KWDA")                  ),
            new(Id: "WeapMaterialGlass",                      Formkey: Helpers.ParseFormKey("Skyrim.esm|0001e71d|KWDA")                  ),
            new(Id: "WeapMaterialEbony",                      Formkey: Helpers.ParseFormKey("Skyrim.esm|0001e71e|KWDA")                  ),
            new(Id: "WeapMaterialDaedric",                    Formkey: Helpers.ParseFormKey("Skyrim.esm|0001e71f|KWDA")                  ),
            new(Id: "ArmorHeavy",                             Formkey: Helpers.ParseFormKey("Skyrim.esm|0006bbd2|KWDA")                  ),
            new(Id: "ArmorLight",                             Formkey: Helpers.ParseFormKey("Skyrim.esm|0006bbd3|KWDA")                  ),
            new(Id: "ArmorMaterialDaedric",                   Formkey: Helpers.ParseFormKey("Skyrim.esm|0006bbd4|KWDA")                  ),
            new(Id: "ArmorMaterialDragonplate",               Formkey: Helpers.ParseFormKey("Skyrim.esm|0006bbd5|KWDA")                  ),
            new(Id: "ArmorMaterialDragonscale",               Formkey: Helpers.ParseFormKey("Skyrim.esm|0006bbd6|KWDA")                  ),
            new(Id: "ArmorMaterialDwarven",                   Formkey: Helpers.ParseFormKey("Skyrim.esm|0006bbd7|KWDA")                  ),
            new(Id: "ArmorMaterialEbony",                     Formkey: Helpers.ParseFormKey("Skyrim.esm|0006bbd8|KWDA")                  ),
            new(Id: "ArmorMaterialElven",                     Formkey: Helpers.ParseFormKey("Skyrim.esm|0006bbd9|KWDA")                  ),
            new(Id: "ArmorMaterialElvenGilded",               Formkey: Helpers.ParseFormKey("Skyrim.esm|0006bbda|KWDA")                  ),
            new(Id: "ArmorMaterialLeather",                   Formkey: Helpers.ParseFormKey("Skyrim.esm|0006bbdb|KWDA")                  ),
            new(Id: "ArmorMaterialGlass",                     Formkey: Helpers.ParseFormKey("Skyrim.esm|0006bbdc|KWDA")                  ),
            new(Id: "ArmorMaterialHide",                      Formkey: Helpers.ParseFormKey("Skyrim.esm|0006bbdd|KWDA")                  ),
            new(Id: "ArmorMaterialScaled",                    Formkey: Helpers.ParseFormKey("Skyrim.esm|0006bbde|KWDA")                  ),
            new(Id: "ArmorMaterialStudded",                   Formkey: Helpers.ParseFormKey("Skyrim.esm|0006bbdf|KWDA")                  ),
            new(Id: "ArmorMaterialImperialLight",             Formkey: Helpers.ParseFormKey("Skyrim.esm|0006bbe0|KWDA")                  ),
            new(Id: "ArmorMaterialImperialStudded",           Formkey: Helpers.ParseFormKey("Skyrim.esm|0006bbe1|KWDA")                  ),
            new(Id: "ArmorMaterialImperialHeavy",             Formkey: Helpers.ParseFormKey("Skyrim.esm|0006bbe2|KWDA")                  ),
            new(Id: "ArmorMaterialIron",                      Formkey: Helpers.ParseFormKey("Skyrim.esm|0006bbe3|KWDA")                  ),
            new(Id: "ArmorMaterialIronBanded",                Formkey: Helpers.ParseFormKey("Skyrim.esm|0006bbe4|KWDA")                  ),
            new(Id: "ArmorMaterialOrcish",                    Formkey: Helpers.ParseFormKey("Skyrim.esm|0006bbe5|KWDA")                  ),
            new(Id: "ArmorMaterialSteel",                     Formkey: Helpers.ParseFormKey("Skyrim.esm|0006bbe6|KWDA")                  ),
            new(Id: "ArmorMaterialSteelPlate",                Formkey: Helpers.ParseFormKey("Skyrim.esm|0006bbe7|KWDA")                  ),
            new(Id: "ArmorClothing",                          Formkey: Helpers.ParseFormKey("Skyrim.esm|0006bbe8|KWDA")                  ),
            new(Id: "ArmorJewelry",                           Formkey: Helpers.ParseFormKey("Skyrim.esm|0006bbe9|KWDA")                  ),
            new(Id: "ArmorSlotCuirass",                       Formkey: Helpers.ParseFormKey("Skyrim.esm|0006c0ec|KWDA")                  ),
            new(Id: "ArmorSlotBoots",                         Formkey: Helpers.ParseFormKey("Skyrim.esm|0006c0ed|KWDA")                  ),
            new(Id: "ArmorSlotHelmet",                        Formkey: Helpers.ParseFormKey("Skyrim.esm|0006c0ee|KWDA")                  ),
            new(Id: "ArmorSlotGauntlets",                     Formkey: Helpers.ParseFormKey("Skyrim.esm|0006c0ef|KWDA")                  ),
            new(Id: "WeapTypeWarhammer",                      Formkey: Helpers.ParseFormKey("Skyrim.esm|0006d930|KWDA")                  ),
            new(Id: "WeapTypeGreatsword",                     Formkey: Helpers.ParseFormKey("Skyrim.esm|0006d931|KWDA")                  ),
            new(Id: "WeapTypeBattleaxe",                      Formkey: Helpers.ParseFormKey("Skyrim.esm|0006d932|KWDA")                  ),
            new(Id: "CraftingTanningRack",                    Formkey: Helpers.ParseFormKey("Skyrim.esm|0007866a|KWDA")                  ),
            new(Id: "CraftingSmithingForge",                  Formkey: Helpers.ParseFormKey("Skyrim.esm|00088105|KWDA")                  ),
            new(Id: "CraftingSmithingSharpeningWheel",        Formkey: Helpers.ParseFormKey("Skyrim.esm|00088108|KWDA")                  ),
            new(Id: "VendorItemArmor",                        Formkey: Helpers.ParseFormKey("Skyrim.esm|0008f959|KWDA")                  ),
            new(Id: "VendorItemJewelry",                      Formkey: Helpers.ParseFormKey("Skyrim.esm|0008f95a|KWDA")                  ),
            new(Id: "VendorItemClothing",                     Formkey: Helpers.ParseFormKey("Skyrim.esm|0008f95b|KWDA")                  ),
            new(Id: "ArmorShield",                            Formkey: Helpers.ParseFormKey("Skyrim.esm|000965b2|KWDA")                  ),
            new(Id: "CraftingSmelter",                        Formkey: Helpers.ParseFormKey("Skyrim.esm|000a5cce|KWDA")                  ),
            new(Id: "ClothingBody",                           Formkey: Helpers.ParseFormKey("Skyrim.esm|000a8657|KWDA")                  ),
            new(Id: "ArmorMaterialStormcloak",                Formkey: Helpers.ParseFormKey("Skyrim.esm|000ac13a|KWDA")                  ),
            new(Id: "CraftingSmithingArmorTable",             Formkey: Helpers.ParseFormKey("Skyrim.esm|000adb78|KWDA")                  ),
            new(Id: "MagicDisallowEnchanting",                Formkey: Helpers.ParseFormKey("Skyrim.esm|000c27bd|KWDA")                  ),
            new(Id: "WeapMaterialImperial",                   Formkey: Helpers.ParseFormKey("Skyrim.esm|000c5c00|KWDA")                  ),
            new(Id: "WeapMaterialDraugr",                     Formkey: Helpers.ParseFormKey("Skyrim.esm|000c5c01|KWDA")                  ),
            new(Id: "WeapMaterialDraugrHoned",                Formkey: Helpers.ParseFormKey("Skyrim.esm|000c5c02|KWDA")                  ),
            new(Id: "WeapMaterialFalmer",                     Formkey: Helpers.ParseFormKey("Skyrim.esm|000c5c03|KWDA")                  ),
            new(Id: "WeapMaterialFalmerHoned",                Formkey: Helpers.ParseFormKey("Skyrim.esm|000c5c04|KWDA")                  ),
            new(Id: "WeapMaterialSilver",                     Formkey: Helpers.ParseFormKey("Skyrim.esm|0010aa1a|KWDA")                  ),
            new(Id: "ClothingHead",                           Formkey: Helpers.ParseFormKey("Skyrim.esm|0010cd11|KWDA")                  ),
            new(Id: "ArmorNightingale",                       Formkey: Helpers.ParseFormKey("Skyrim.esm|0010fd61|KWDA")                  ),
            new(Id: "ArmorDarkBrotherhood",                   Formkey: Helpers.ParseFormKey("Skyrim.esm|0010fd62|KWDA")                  ),
            new(Id: "ArmorMaterialBlades",                    Formkey: Helpers.ParseFormKey("Update.esm|000009c0|KWDA")                  ),
            new(Id: "ArmorMaterialForsworn",                  Formkey: Helpers.ParseFormKey("Update.esm|000009b9|KWDA")                  ),
            new(Id: "ArmorMaterialThievesGuild",              Formkey: Helpers.ParseFormKey("Update.esm|000009bc|KWDA")                  ),
            new(Id: "ArmorMaterialBearStormcloak",            Formkey: Helpers.ParseFormKey("Update.esm|000009be|KWDA")                  ),
            new(Id: "WAF_WeapMaterialBlades",                 Formkey: Helpers.ParseFormKey("Update.esm|00af0103|KWDA")                  ),
            new(Id: "WAF_WeapMaterialForsworn",               Formkey: Helpers.ParseFormKey("Update.esm|00af0104|KWDA")                  ),
            new(Id: "WAF_ArmorWolf",                          Formkey: Helpers.ParseFormKey("Update.esm|00af0107|KWDA")                  ),
            new(Id: "WAF_ArmorMaterialGuard",                 Formkey: Helpers.ParseFormKey("Update.esm|00af0112|KWDA")                  ),
            new(Id: "WAF_DLC1WeapMaterialDawnguard",          Formkey: Helpers.ParseFormKey("Update.esm|00af0116|KWDA")                  ),
            new(Id: "WAF_DLC1ArmorDawnguardHeavy",            Formkey: Helpers.ParseFormKey("Update.esm|00af0117|KWDA")                  ),
            new(Id: "WAF_DLC1ArmorDawnguardLight",            Formkey: Helpers.ParseFormKey("Update.esm|00af0118|KWDA")                  ),
            new(Id: "WAF_ArmorMaterialDraugr",                Formkey: Helpers.ParseFormKey("Update.esm|00af0135|KWDA")                  ),
            new(Id: "WAF_ArmorMaterialThalmor",               Formkey: Helpers.ParseFormKey("Update.esm|00af0222|KWDA")                  ),
            new(Id: "DLC1CrossbowIsEnhanced",                 Formkey: Helpers.ParseFormKey("Dawnguard.esm|0000399c|KWDA")               ),
            new(Id: "DLC1ArmorMaterialHunter",                Formkey: Helpers.ParseFormKey("Dawnguard.esm|000050c4|KWDA")               ),
            new(Id: "DLC1CraftingDawnguard",                  Formkey: Helpers.ParseFormKey("Dawnguard.esm|0000f806|KWDA")               ),
            new(Id: "DLC1ArmorMaterialDawnguard",             Formkey: Helpers.ParseFormKey("Dawnguard.esm|00012ccd|KWDA")               ),
            new(Id: "DLC1ArmorMaterialFalmerHardened",        Formkey: Helpers.ParseFormKey("Dawnguard.esm|00012cce|KWDA")               ),
            new(Id: "DLC1ArmorMaterialFalmerHeavy",           Formkey: Helpers.ParseFormKey("Dawnguard.esm|00012ccf|KWDA")               ),
            new(Id: "DLC1ArmorMaterialFalmerHeavyOriginal",   Formkey: Helpers.ParseFormKey("Dawnguard.esm|00012cd0|KWDA")               ),
            new(Id: "DLC1ArmorMaterialVampire",               Formkey: Helpers.ParseFormKey("Dawnguard.esm|0001463e|KWDA")               ),
            new(Id: "DLC1WeapMaterialDragonbone",             Formkey: Helpers.ParseFormKey("Dawnguard.esm|00019822|KWDA")               ),
            new(Id: "DLC2ArmorMaterialBonemoldLight",         Formkey: Helpers.ParseFormKey("Dragonborn.esm|00024100|KWDA")              ),
            new(Id: "DLC2ArmorMaterialBonemoldHeavy",         Formkey: Helpers.ParseFormKey("Dragonborn.esm|00024101|KWDA")              ),
            new(Id: "DLC2ArmorMaterialChitinLight",           Formkey: Helpers.ParseFormKey("Dragonborn.esm|00024102|KWDA")              ),
            new(Id: "DLC2ArmorMaterialChitinHeavy",           Formkey: Helpers.ParseFormKey("Dragonborn.esm|00024103|KWDA")              ),
            new(Id: "DLC2ArmorMaterialNordicLight",           Formkey: Helpers.ParseFormKey("Dragonborn.esm|00024104|KWDA")              ),
            new(Id: "DLC2ArmorMaterialNordicHeavy",           Formkey: Helpers.ParseFormKey("Dragonborn.esm|00024105|KWDA")              ),
            new(Id: "DLC2ArmorMaterialStalhrimHeavy",         Formkey: Helpers.ParseFormKey("Dragonborn.esm|00024106|KWDA")              ),
            new(Id: "DLC2ArmorMaterialStalhrimLight",         Formkey: Helpers.ParseFormKey("Dragonborn.esm|00024107|KWDA")              ),
            new(Id: "DLC2WeaponMaterialStalhrim",             Formkey: Helpers.ParseFormKey("Dragonborn.esm|0002622f|KWDA")              ),
            new(Id: "DLC2WeaponMaterialNordic",               Formkey: Helpers.ParseFormKey("Dragonborn.esm|00026230|KWDA")              ),
            new(Id: "cc_ArmorMaterialGolden",                 Formkey: Helpers.ParseFormKey("ccBGSSSE025-AdvDSGS.esm|0021bd63|KWDA")     ),
            new(Id: "cc_ArmorMaterialDark",                   Formkey: Helpers.ParseFormKey("ccBGSSSE025-AdvDSGS.esm|0021bd64|KWDA")     ),
            new(Id: "cc_ArmorMaterialMadness",                Formkey: Helpers.ParseFormKey("ccBGSSSE025-AdvDSGS.esm|0021bd65|KWDA")     ),
            new(Id: "cc_ArmorMaterialAmber",                  Formkey: Helpers.ParseFormKey("ccBGSSSE025-AdvDSGS.esm|0021bd66|KWDA")     ),
            new(Id: "cc_WeapMaterialAmber",                   Formkey: Helpers.ParseFormKey("ccBGSSSE025-AdvDSGS.esm|0021bd67|KWDA")     ),
            new(Id: "cc_WeapMaterialMadness",                 Formkey: Helpers.ParseFormKey("ccBGSSSE025-AdvDSGS.esm|0021bd68|KWDA")     ),
            new(Id: "cc_WeapMaterialGolden",                  Formkey: Helpers.ParseFormKey("ccBGSSSE025-AdvDSGS.esm|0021bd69|KWDA")     ),
            new(Id: "cc_WeapMaterialDark",                    Formkey: Helpers.ParseFormKey("ccBGSSSE025-AdvDSGS.esm|0021bd6a|KWDA")     ),
            new(Id: "skyre__NoMeltdownRecipes",               Formkey: Helpers.ParseFormKey("Skyrim AE Redone - Core.esm|0000080e|KWDA") ),
            new(Id: "skyre__ArmorShieldHeavy",                Formkey: Helpers.ParseFormKey("Skyrim AE Redone - Core.esm|0000080f|KWDA") ),
            new(Id: "skyre__ArmorShieldLight",                Formkey: Helpers.ParseFormKey("Skyrim AE Redone - Core.esm|00000810|KWDA") ),
            new(Id: "skyre__ArmorDreamcloth",                 Formkey: Helpers.ParseFormKey("Skyrim AE Redone - Core.esm|00000811|KWDA") ),
            new(Id: "skyre__WeapTypeBastardSword",            Formkey: Helpers.ParseFormKey("Skyrim AE Redone - Core.esm|00000813|KWDA") ),
            new(Id: "skyre__WeapTypeQuarterstaff",            Formkey: Helpers.ParseFormKey("Skyrim AE Redone - Core.esm|00000814|KWDA") ),
            new(Id: "skyre__WeapMaterialBound",               Formkey: Helpers.ParseFormKey("Skyrim AE Redone - Core.esm|00000815|KWDA") ),
            new(Id: "skyre__WeapTypeShortbow",                Formkey: Helpers.ParseFormKey("Skyrim AE Redone - Core.esm|00000817|KWDA") ),
            new(Id: "skyre__WeapTypeBroadsword",              Formkey: Helpers.ParseFormKey("Skyrim AE Redone - Core.esm|00000818|KWDA") ),
            new(Id: "skyre__WeapTypeClub",                    Formkey: Helpers.ParseFormKey("Skyrim AE Redone - Core.esm|00000819|KWDA") ),
            new(Id: "skyre__WeapTypeCrossbow",                Formkey: Helpers.ParseFormKey("Skyrim AE Redone - Core.esm|0000081a|KWDA") ),
            new(Id: "skyre__WeapTypeGlaive",                  Formkey: Helpers.ParseFormKey("Skyrim AE Redone - Core.esm|0000081b|KWDA") ),
            new(Id: "skyre__WeapTypeHalberd",                 Formkey: Helpers.ParseFormKey("Skyrim AE Redone - Core.esm|0000081c|KWDA") ),
            new(Id: "skyre__WeapTypeHatchet",                 Formkey: Helpers.ParseFormKey("Skyrim AE Redone - Core.esm|0000081d|KWDA") ),
            new(Id: "skyre__WeapTypeKatana",                  Formkey: Helpers.ParseFormKey("Skyrim AE Redone - Core.esm|0000081e|KWDA") ),
            new(Id: "skyre__WeapTypeLongbow",                 Formkey: Helpers.ParseFormKey("Skyrim AE Redone - Core.esm|00000816|KWDA") ),
            new(Id: "skyre__WeapTypeLongmace",                Formkey: Helpers.ParseFormKey("Skyrim AE Redone - Core.esm|0000081f|KWDA") ),
            new(Id: "skyre__WeapTypeLongspear",               Formkey: Helpers.ParseFormKey("Skyrim AE Redone - Core.esm|00000820|KWDA") ),
            new(Id: "skyre__WeapTypeLongsword",               Formkey: Helpers.ParseFormKey("Skyrim AE Redone - Core.esm|00000821|KWDA") ),
            new(Id: "skyre__WeapTypeMaul",                    Formkey: Helpers.ParseFormKey("Skyrim AE Redone - Core.esm|00000822|KWDA") ),
            new(Id: "skyre__WeapTypeNodachi",                 Formkey: Helpers.ParseFormKey("Skyrim AE Redone - Core.esm|00000823|KWDA") ),
            new(Id: "skyre__WeapTypeScimitar",                Formkey: Helpers.ParseFormKey("Skyrim AE Redone - Core.esm|00000824|KWDA") ),
            new(Id: "skyre__WeapTypeShortspear",              Formkey: Helpers.ParseFormKey("Skyrim AE Redone - Core.esm|00000825|KWDA") ),
            new(Id: "skyre__WeapTypeShortsword",              Formkey: Helpers.ParseFormKey("Skyrim AE Redone - Core.esm|00000826|KWDA") ),
            new(Id: "skyre__WeapTypeTanto",                   Formkey: Helpers.ParseFormKey("Skyrim AE Redone - Core.esm|00000827|KWDA") ),
            new(Id: "skyre__WeapTypeWakizashi",               Formkey: Helpers.ParseFormKey("Skyrim AE Redone - Core.esm|00000828|KWDA") ),
            new(Id: "skyre__WeapMaterialSilverRefined",       Formkey: Helpers.ParseFormKey("Skyrim AE Redone - Core.esm|00000829|KWDA") ),
            new(Id: "skyre__DreamclothBody",                  Formkey: Helpers.ParseFormKey("Skyrim AE Redone - Core.esm|0000098d|KWDA") ),
            new(Id: "skyre_ENCAmmoSiphoningKeyword",          Formkey: Helpers.ParseFormKey("Skyrim AE Redone - Core.esm|00000b8f|KWDA") ),
            new(Id: "skyre_MARAmmoBarbedKeyword",             Formkey: Helpers.ParseFormKey("Skyrim AE Redone - Core.esm|00000d87|KWDA") ),
            new(Id: "skyre_MARAmmoHeavyKeyword",              Formkey: Helpers.ParseFormKey("Skyrim AE Redone - Core.esm|00000d88|KWDA") ),
            new(Id: "skyre_MAREnhancedCrossbowMuffled",       Formkey: Helpers.ParseFormKey("Skyrim AE Redone - Core.esm|00000d97|KWDA") ),
            new(Id: "skyre_MAREnhancedCrossbowSiege",         Formkey: Helpers.ParseFormKey("Skyrim AE Redone - Core.esm|00000d98|KWDA") ),
            new(Id: "skyre_SPCMasqueradeBandit",              Formkey: Helpers.ParseFormKey("Skyrim AE Redone - Core.esm|00000f44|KWDA") ),
            new(Id: "skyre_SPCMasqueradeForsworn",            Formkey: Helpers.ParseFormKey("Skyrim AE Redone - Core.esm|00000f45|KWDA") ),
            new(Id: "skyre_SPCMasqueradeImperial",            Formkey: Helpers.ParseFormKey("Skyrim AE Redone - Core.esm|00000f46|KWDA") ),
            new(Id: "skyre_SPCMasqueradeStormcloak",          Formkey: Helpers.ParseFormKey("Skyrim AE Redone - Core.esm|00000f47|KWDA") ),
            new(Id: "skyre_SPCMasqueradeThalmor",             Formkey: Helpers.ParseFormKey("Skyrim AE Redone - Core.esm|00000f48|KWDA") ),
            new(Id: "ArcaneBlacksmith",                       Formkey: Helpers.ParseFormKey("Skyrim.esm|0005218e|PERK")                  ),
            new(Id: "DragonArmor",                            Formkey: Helpers.ParseFormKey("Skyrim.esm|00052190|PERK")                  ),
            new(Id: "SteelSmithing",                          Formkey: Helpers.ParseFormKey("Skyrim.esm|000cb40d|PERK")                  ),
            new(Id: "DwarvenSmithing",                        Formkey: Helpers.ParseFormKey("Skyrim.esm|000cb40e|PERK")                  ),
            new(Id: "ElvenSmithing",                          Formkey: Helpers.ParseFormKey("Skyrim.esm|000cb40f|PERK")                  ),
            new(Id: "OrcishSmithing",                         Formkey: Helpers.ParseFormKey("Skyrim.esm|000cb410|PERK")                  ),
            new(Id: "GlassSmithing",                          Formkey: Helpers.ParseFormKey("Skyrim.esm|000cb411|PERK")                  ),
            new(Id: "EbonySmithing",                          Formkey: Helpers.ParseFormKey("Skyrim.esm|000cb412|PERK")                  ),
            new(Id: "DaedricSmithing",                        Formkey: Helpers.ParseFormKey("Skyrim.esm|000cb413|PERK")                  ),
            new(Id: "AdvancedArmors",                         Formkey: Helpers.ParseFormKey("Skyrim.esm|000cb414|PERK")                  ),
            new(Id: "SilverPerk",                             Formkey: Helpers.ParseFormKey("Skyrim.esm|0010d685|PERK")                  ),
            new(Id: "DLC1EnchancedCrossbowArmorPiercingPerk", Formkey: Helpers.ParseFormKey("Dawnguard.esm|0000399b|PERK")               ),
            new(Id: "skyre_ALCFuse",                          Formkey: Helpers.ParseFormKey("Skyrim AE Redone - Core.esm|00000851|PERK") ),
            new(Id: "skyre_ALCSuffocation",                   Formkey: Helpers.ParseFormKey("Skyrim AE Redone - Core.esm|00000873|PERK") ),
            new(Id: "skyre_MARAdvancedFletching0",            Formkey: Helpers.ParseFormKey("Skyrim AE Redone - Core.esm|00000d84|PERK") ),
            new(Id: "skyre_MARAdvancedFletching1",            Formkey: Helpers.ParseFormKey("Skyrim AE Redone - Core.esm|00000d85|PERK") ),
            new(Id: "skyre_MARAdvancedFletching2",            Formkey: Helpers.ParseFormKey("Skyrim AE Redone - Core.esm|00000d86|PERK") ),
            new(Id: "skyre_ENCElementalBombard0",             Formkey: Helpers.ParseFormKey("Skyrim AE Redone - Core.esm|00000b8d|PERK") ),
            new(Id: "skyre_ENCElementalBombard1",             Formkey: Helpers.ParseFormKey("Skyrim AE Redone - Core.esm|00000b8e|PERK") ),
            new(Id: "skyre_MARBallistics",                    Formkey: Helpers.ParseFormKey("Skyrim AE Redone - Core.esm|00000d80|PERK") ),
            new(Id: "skyre_MARCrossbowLight",                 Formkey: Helpers.ParseFormKey("Skyrim AE Redone - Core.esm|00000d93|PERK") ),
            new(Id: "skyre_MARCrossbowRecurve",               Formkey: Helpers.ParseFormKey("Skyrim AE Redone - Core.esm|00000d94|PERK") ),
            new(Id: "skyre_MARCrossbowMuffled",               Formkey: Helpers.ParseFormKey("Skyrim AE Redone - Core.esm|00000d95|PERK") ),
            new(Id: "skyre_MARCrossbowSiege",                 Formkey: Helpers.ParseFormKey("Skyrim AE Redone - Core.esm|00000d96|PERK") ),
            new(Id: "skyre_MARArtificer",                     Formkey: Helpers.ParseFormKey("Skyrim AE Redone - Core.esm|00000dbf|PERK") ),
            new(Id: "skyre_SMTLeathercraft",                  Formkey: Helpers.ParseFormKey("Skyrim AE Redone - Core.esm|00000ec4|PERK") ),
            new(Id: "skyre_SMTMeltdown",                      Formkey: Helpers.ParseFormKey("Skyrim AE Redone - Core.esm|00000edf|PERK") ),
            new(Id: "skyre_SMTTradecraft",                    Formkey: Helpers.ParseFormKey("Skyrim AE Redone - Core.esm|00000ee0|PERK") ),
            new(Id: "skyre_SMTWeavingMill",                   Formkey: Helpers.ParseFormKey("Skyrim AE Redone - Core.esm|00000ee1|PERK") ),
            new(Id: "skyre_SMTDeepSilver",                    Formkey: Helpers.ParseFormKey("Skyrim AE Redone - Core.esm|00000ee4|PERK") )
        ];
}